log "/bird.log" { warning, error, auth, fatal, bug };
protocol device {
}
protocol direct {
    disabled;       # Disable by default
    ipv4;           # Connect to default IPv4 table
    ipv6;           # ... and to default IPv6 table
}
protocol kernel {
    ipv4 {          # Connect protocol to IPv4 table by channel
        export all; # Export to protocol. default is export none
    };
}
# protocol static {
#     ipv4;           # Again, IPv6 channel with default options
# }
protocol ospf{
    ipv4 {
        import all;
    };
    area 0 {
        interface "SH*O*S*" {
            type broadcast; # Detected by default
            cost 10;
            hello 5;
        };
        interface "GS*" {
            type broadcast; # Detected by default
            cost 10;
            hello 5;
        };
        interface "POP" {
            type broadcast; # Detected by default
            cost 10;
            hello 5;
        };
        interface "eth*" {
            type broadcast; # Detected by default
            cost 10;
            hello 5;
        };
    };
}
